[tool.poetry]
name = "actions-core"
version = "1.0.0"
description = "Actions Core"
authors = ["Sema4.ai, Inc. <dev@sema4.ai>"]
readme = "README.md"
repository = "https://github.com/Sema4AI/actions/"
license = "Apache-2.0"
packages = [{ include = "actions", from = "src" }]

[tool.poetry.dependencies]
python = "^3.10"
cryptography = ">=44.0.1"
robocorp-log = ">=2.4,<4"
robocorp-truststore = ">=0.8.0"
psutil = ">=5.0,<8.0"
docstring_parser_fork = "^0.0.5"
pydantic = "^2.11.7"
actions-http-helper = "^1.0.0"
pyyaml = "^6.0"

[tool.poetry.group.optional.dependencies]
pyarrow = "^15.0"

[tool.poetry.group.dev.dependencies]
actions-local-devutils = { path = "../devutils/", develop = true }
types-psutil = ">=5.9,<8.0"
types-PyYAML = "6.0"

[tool.mypy]
mypy_path = "src:tests"
ignore_missing_imports = true

[tool.black]
skip-string-normalization = false
skip-magic-trailing-comma = false

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
