"""
This script generates the github actions workflows.

To run it:
  python _gen_workflows.py

To add new targets, create a new class that inherits from BaseWorkflow
(or BaseTests) and add it to the TARGETS list.

Override the methods you need to change to customize the generated workflow.
 -- usually `build_steps` in BaseWorkflow and `run_tests` in BaseTests
 -- it's fine to override other needed methods as well

Given that this will always regenerate the workflows, feel free to make
refactorings in the structure as needed.
"""

from collections.abc import Iterator
from pathlib import Path

import yaml
from typing_extensions import override

CURDIR = Path(__file__).absolute().parent

run_in_env = "uv run --no-project --python ${{ matrix.python }} "

AUTO_GEN_HEADER = """# Important!!
# This file is auto-generated by running:
#
#   python _gen_workflows.py
#
# Do not edit it directly, your changes will be lost!
# Instead, edit `_gen_workflows.py` with the required
# changes and rerun that script (or manually change
# this file, but before the final version
# make sure that you update the `_gen_workflows.py`
# script to match the changes you made here
# and rerun the script).
"""


# No need to check if it's a beta release
NOT_BETA_IF_CLAUSE = "${{ !endsWith(github.ref_name, '-beta') }}"
UBUNTU_VERSION = "ubuntu-22.04"


def collect_deps_pyprojects(root_pyproject: Path, found=None) -> Iterator[Path]:
    if found is None:
        found = set()

    import tomlkit  # allows roundtrip of toml files

    contents: dict = tomlkit.loads(root_pyproject.read_bytes().decode("utf-8"))

    poetry = contents.get("tool", {}).get("poetry", {})
    project = contents.get("project", {})
    dependencies = list(poetry.get("dependencies", {}))
    dependencies.extend(poetry.get("group", {}).get("dev", {}).get("dependencies", {}))
    dependencies.extend(
        dependency.partition(">=")[0].partition("[")[0].strip()
        for dependency in project.get("dependencies", [])
    )
    for optional in project.get("optional-dependencies", {}).values():
        dependencies.extend(
            dependency.partition(">=")[0].partition("[")[0].strip()
            for dependency in optional
        )
    owned_directories = {
        "actions-core": "actions",
        "actions-runtime": "action_server",
        "actions-http-helper": "actions-http-helper",
        "actions-work-items": "work-items",
        "actions-local-devutils": "devutils",
    }
    for key in dependencies:
        directory = owned_directories.get(key)
        if directory is None:
            continue
        dep_pyproject = root_pyproject.parent.parent / directory / "pyproject.toml"
        assert dep_pyproject.exists(), f"Expected {dep_pyproject} to exist."
        if dep_pyproject not in found:
            found.add(dep_pyproject)
            yield dep_pyproject
            yield from collect_deps_pyprojects(dep_pyproject, found)


def get_python_version(pyproject):
    import tomlkit

    contents: dict = tomlkit.loads(pyproject.read_bytes().decode("utf-8"))
    dependencies = contents.get("tool", {}).get("poetry", {}).get("dependencies", {})
    for key, value in dependencies.items():
        if key == "python":
            version = value.strip("^")
            assert "." in version

            # Extract the first major minor from ">=3.11.0,<3.12"
            if "," in version:
                version = version.split(",")[0]

            version = version.strip(">=")

            assert tuple(int(x) for x in version.split(".")) > (
                3,
                7,
            ), f"Bad version: {version}. pyproject: {pyproject}"
            return version
    requires_python = contents.get("project", {}).get("requires-python")
    if requires_python:
        version = requires_python.lstrip(">=").split(",")[0]
        assert tuple(int(x) for x in version.split(".")) > (3, 7)
        return version
    raise RuntimeError(f"Unable to get python version in: {pyproject}")


class BaseWorkflow:
    fail_fast = False

    def __init__(self):
        project_dir = CURDIR.parent.parent / self.project_name
        assert project_dir.exists(), f"{project_dir} does not exist"

        self.target_file = CURDIR / f"{self.target}"
        paths = [
            f"{self.project_name}/**",
            f".github/workflows/{self.target}",
            "devutils/**",
        ]

        pyproject_toml_file = project_dir / "pyproject.toml"
        self.pyproject_toml_file = pyproject_toml_file
        self.minimum_python_version = get_python_version(pyproject_toml_file)

        dep_pyprojects = list(collect_deps_pyprojects(pyproject_toml_file))
        for dep_pyproject in dep_pyprojects:
            dep_name = dep_pyproject.parent.name
            add_dep = f"{dep_name}/**"
            if add_dep not in paths:
                paths.append(add_dep)

        self.full = {}
        self.full.update({"name": self.name})
        permissions = {"contents": "read", "id-token": "write"}
        if self.target == "actions_runtime_pypi_release.yml":
            permissions = {"contents": "read"}
        self.full.update({"permissions": permissions})
        self.full.update(self.on_part(paths))
        self.full.update(self.defaults_part())
        self.full.update(self.jobs_part())

    def setup_python(self, pinned=False):
        return [
            # {
            # "name": "Set up Python ${{ matrix.python }}",
            # "uses": "actions/setup-python@v5",
            # "with": {
            #     "python-version": "${{ matrix.python }}",
            #     "cache": "poetry",
            # },
            {
                "name": "Install the latest version of uv",
                "uses": "astral-sh/setup-uv@e58605a9b6da7c637471fab8847a5e5a6b8df081"
                if pinned
                else "astral-sh/setup-uv@v5",
                "with": {
                    "enable-cache": True,
                },
            },
            {
                "name": f"Install Python {self.minimum_python_version}",
                "run": f"uv python install {self.minimum_python_version}",
            },
        ]

    def matrix(self, pyversion: str):
        matrix = {
            "name": [
                f"ubuntu-py{pyversion}-devmode",
                f"windows-py{pyversion}-devmode",
                f"macos-py{pyversion}-devmode",
            ],
            "include": [
                {
                    "name": f"ubuntu-py{pyversion}-devmode",
                    "python": pyversion,
                    "os": UBUNTU_VERSION,
                },
                {
                    "name": f"windows-py{pyversion}-devmode",
                    "python": pyversion,
                    "os": "windows-2022",
                },
                {
                    "name": f"macos-py{pyversion}-devmode",
                    "os": "macos-15",
                    "python": pyversion,
                },
            ],
        }
        return matrix

    def matrix_binary_release(self, pyversion: str):
        return {
            # Important: Changing os requires updating the related references in this yml.
            "os": [
                UBUNTU_VERSION,
                "windows-2022",
                "macos-15",  # used for the arm64 binary
            ],
            "include": [
                {
                    "os": UBUNTU_VERSION,
                    "python": pyversion,
                    "name": "linux",
                    "asset_path": "action_server/dist/final/action-server",
                },
                {
                    "os": "windows-2022",
                    "python": pyversion,
                    "name": "windows",
                    "asset_path": "action_server/dist/final/action-server.exe",
                },
                {
                    "os": "macos-15",
                    "python": pyversion,
                    "name": "macos",
                    "asset_path": "action_server/dist/final/action-server",
                },
            ],
        }

    def matrix_cibuildwheel(self, pyversion: str):
        return {
            # Important: Changing os requires updating the related references in this yml.
            "os": [
                UBUNTU_VERSION,
                "windows-2022",
                "macos-15",  # used for the arm64 binary
            ],
            "include": [
                {
                    "os": UBUNTU_VERSION,
                    "python": pyversion,
                },
                {
                    "os": "windows-2022",
                    "python": pyversion,
                },
                {
                    "os": "macos-15",
                    "python": pyversion,
                },
            ],
        }

    def matrix_ubuntu(self, pyversion: str):
        matrix = {
            "name": [
                f"ubuntu-py{pyversion}",
            ],
            "include": [
                {
                    "name": f"ubuntu-py{pyversion}",
                    "python": pyversion,
                    "os": UBUNTU_VERSION,
                },
            ],
        }
        return matrix

    def jobs_part(self):
        return {"jobs": {"build": self.build_job_part()}}

    def build_job_part(self):
        build = {}
        build.update(self.runs_on_and_strategy_part())
        build.update(self.build_steps_part())
        return build

    def build_steps_part(self):
        return {"steps": self.build_steps()}

    def runs_on_and_strategy_part(self):
        return {
            "runs-on": "${{ matrix.os }}",
            "strategy": {
                "fail-fast": self.fail_fast,
                "matrix": self.matrix(self.minimum_python_version),
            },
        }

    def defaults_part(self):
        return {"defaults": {"run": {"working-directory": f"./{self.project_name}"}}}

    def on_part(self, dep_paths):
        return {
            "on": {
                "push": {
                    "branches": ["master", "wip"],
                    "paths": dep_paths[:],
                },
                "pull_request": {
                    "branches": ["master"],
                    "paths": dep_paths[:],
                },
            }
        }

    def generate(self):
        contents = yaml.safe_dump(self.full, sort_keys=False)
        path = CURDIR / self.target
        final_header = AUTO_GEN_HEADER.rstrip("\n") if self.target == "actions_runtime_recovery.yml" else AUTO_GEN_HEADER
        print("Writing to ", path)
        path.write_text(
            f"""{AUTO_GEN_HEADER}

{contents}

{final_header}
""",
            "utf-8",
        )

    def is_beta_in_outputs(self):
        # A step defining if it's a beta release. Needs 2 things:
        # 1. Add to the outputs
        # 2. Add to the steps
        # 3. Add to the needs
        # Can then be checked with:
        #    if: ${{ needs.<job-name>.outputs.is_beta == 'false' }}
        #
        output = {
            "is_beta": "${{ steps.check_beta.outputs.is_beta }}",
        }
        return output

    def is_beta_in_steps(self):
        step = {
            "name": "Check if this is a beta release",
            "id": "check_beta",
            "run": """
is_beta=${{ endsWith(github.ref_name, '-beta') }}
echo "is_beta: $is_beta"
echo "is_beta=$is_beta" >> "$GITHUB_OUTPUT"
""",
        }
        return step

    def install_with_devmode(self, env: dict | None = None):
        ret = {
            "name": "Install project (not dev)",
            "if": "contains(matrix.name, '-devmode') == false",
            "run": f"{run_in_env}inv install",
        }
        if env:
            ret["env"] = env.copy()
        return ret

    def install_without_devmode(self, env: dict | None = None):
        ret = {
            "name": "Install project (dev)",
            "if": "contains(matrix.name, '-devmode')",
            "run": f"{run_in_env}inv devinstall",
        }
        if env:
            ret["env"] = env.copy()
        return ret

    def install(self, env: dict | None = None) -> list[dict]:
        return [self.install_with_devmode(env), self.install_without_devmode(env)]

    def setup_node(self, pinned=False):
        return {
            "name": "Setup node",
            "uses": "actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020"
            if pinned
            else "actions/setup-node@v4",
            "with": {
                "node-version": "20.x",
                "registry-url": "https://npm.pkg.github.com",
                "scope": "@robocorp",
            },
        }

    def setup_go(self, pinned=False):
        return {
            "name": "Setup go",
            "uses": "actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff"
            if pinned
            else "actions/setup-go@v5",
            "with": {
                "go-version": "1.23",
                "cache-dependency-path": "action_server/go-wrapper/go.sum",
            },
        }

    def build_frontend(self):
        return {
            "name": "Build frontend",
            "run": f"{run_in_env}inv build-frontend",
            "env": {
                "CI": True,
                "NODE_AUTH_TOKEN": "${{ secrets.GH_PAT_READ_PACKAGES }}",
            },
        }

    def build_oauth2_config(self):
        return {
            "name": "Build OAuth2 config",
            "run": f"{run_in_env}inv build-oauth2-config",
            "env": {"GH_TOKEN": "${{ secrets.GH_PAT_GHA_TO_ANOTHER_REPO }}"},
        }

    def checkout_repo(self, pinned=False):
        return {
            "name": "Checkout repository and submodules",
            "uses": "actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09"
            if pinned
            else "actions/checkout@v5",
        }

    def install_devutils(self, additional_packages: list[str] | None = None):
        run = f"{run_in_env} python -m pip install --break-system-packages -r ../devutils/requirements.txt"
        if additional_packages:
            run += f"\n{run_in_env} python -m pip install --break-system-packages {' '.join(additional_packages)}"
        return {
            "name": "Install devutils requirements",
            "run": run,
        }

    def run_lint(self):
        return {
            "name": "`inv lint`, potentially fixed with `inv pretty`",
            "if": "always()",
            "run": f"{run_in_env}inv lint",
        }

    def run_typecheck(self):
        return {
            "name": "`inv typecheck`",
            "if": "always()",
            "run": f"{run_in_env}inv typecheck",
        }

    def run_docs(self):
        return {
            "name": "`inv docs` with checking on files changed",
            "if": "always()",
            "run": f"{run_in_env}inv docs --check",
        }

    def run_docstrings_validation(self):
        return {
            "name": "`inv docs --validate`",
            "if": "always()",
            "run": f"{run_in_env}inv docs --validate",
        }

    def check_tag_version(self):
        return {
            "name": "Check tag version",
            "run": f"{run_in_env}poetry run inv check-tag-version",
            "if": NOT_BETA_IF_CLAUSE,
        }

    def build_action_server_binary(self):
        return {
            "name": "Build binary",
            "env": {
                "RC_ACTION_SERVER_FORCE_DOWNLOAD_RCC": "true",
                "RC_ACTION_SERVER_DO_SELFTEST": "true",
                "MACOS_SIGNING_CERT": "${{ secrets.MACOS_SIGNING_CERT_ACTIONS_RUNTIME }}",
                "MACOS_SIGNING_CERT_PASSWORD": "${{ secrets.MACOS_SIGNING_CERT_PASSWORD_ACTIONS_RUNTIME }}",
                "MACOS_SIGNING_CERT_NAME": "${{ secrets.MACOS_SIGNING_CERT_NAME_ACTIONS_RUNTIME }}",
                "APPLEID": "${{ secrets.MACOS_APP_ID_FOR_NOTARIZATION_ACTIONS_RUNTIME }}",
                "APPLETEAMID": "${{ secrets.MACOS_TEAM_ID_FOR_NOTARIZATION_ACTIONS_RUNTIME }}",
                "APPLEIDPASS": "${{ secrets.MACOS_APP_ID_PASSWORD_ACTIONS_RUNTIME }}",
                "VAULT_URL": "${{ secrets.WIN_SIGN_AZURE_KEY_VAULT_URL_ACTIONS_RUNTIME }}",
                "CLIENT_ID": "${{ secrets.WIN_SIGN_AZURE_KEY_VAULT_CLIENT_ID_ACTIONS_RUNTIME }}",
                "TENANT_ID": "${{ secrets.WIN_SIGN_AZURE_KEY_VAULT_TENANT_ID_ACTIONS_RUNTIME }}",
                "CLIENT_SECRET": "${{ secrets.WIN_SIGN_AZURE_KEY_VAULT_CLIENT_SECRET_ACTIONS_RUNTIME }}",
                "CERTIFICATE_NAME": "${{ secrets.WIN_SIGN_AZURE_KEY_VAULT_CERTIFICATE_NAME_ACTIONS_RUNTIME }}",
                "GITHUB_EVENT_NAME": "${{ github.event_name }}",
                "GITHUB_REF_NAME": "${{ github.ref_name }}",
                "GITHUB_PR_NUMBER": "${{ github.event.pull_request.number }}",
            },
            "run": f'if [ -n "$MACOS_SIGNING_CERT" ] || [ -n "$VAULT_URL" ]; then {run_in_env}poetry run inv build-executable --sign --go-wrapper; else {run_in_env}poetry run inv build-executable --go-wrapper; fi',
        }

    def build_action_server_binary_cross_platform(
        self, *, ref_name="${{ github.ref_name }}"
    ):
        common_env = {
            "RC_ACTION_SERVER_FORCE_DOWNLOAD_RCC": "true",
            "RC_ACTION_SERVER_DO_SELFTEST": "true",
            "GITHUB_EVENT_NAME": "${{ github.event_name }}",
            "GITHUB_REF_NAME": ref_name,
            "GITHUB_PR_NUMBER": "${{ github.event.pull_request.number }}",
        }
        signing_env = common_env | {
            "MACOS_SIGNING_CERT": "${{ secrets.MACOS_SIGNING_CERT_ACTIONS_RUNTIME }}",
            "MACOS_SIGNING_CERT_PASSWORD": "${{ secrets.MACOS_SIGNING_CERT_PASSWORD_ACTIONS_RUNTIME }}",
            "MACOS_SIGNING_CERT_NAME": "${{ secrets.MACOS_SIGNING_CERT_NAME_ACTIONS_RUNTIME }}",
            "APPLEID": "${{ secrets.MACOS_APP_ID_FOR_NOTARIZATION_ACTIONS_RUNTIME }}",
            "APPLETEAMID": "${{ secrets.MACOS_TEAM_ID_FOR_NOTARIZATION_ACTIONS_RUNTIME }}",
            "APPLEIDPASS": "${{ secrets.MACOS_APP_ID_PASSWORD_ACTIONS_RUNTIME }}",
            "VAULT_URL": "${{ secrets.WIN_SIGN_AZURE_KEY_VAULT_URL_ACTIONS_RUNTIME }}",
            "CLIENT_ID": "${{ secrets.WIN_SIGN_AZURE_KEY_VAULT_CLIENT_ID_ACTIONS_RUNTIME }}",
            "TENANT_ID": "${{ secrets.WIN_SIGN_AZURE_KEY_VAULT_TENANT_ID_ACTIONS_RUNTIME }}",
            "CLIENT_SECRET": "${{ secrets.WIN_SIGN_AZURE_KEY_VAULT_CLIENT_SECRET_ACTIONS_RUNTIME }}",
            "CERTIFICATE_NAME": "${{ secrets.WIN_SIGN_AZURE_KEY_VAULT_CERTIFICATE_NAME_ACTIONS_RUNTIME }}",
        }
        return [
            {
                "name": "Check signing availability",
                "id": "signing",
                "shell": "bash",
                "env": {
                    "SIGNING_EVENT": "${{ github.event_name }}",
                    "SIGNING_OS": "${{ matrix.os }}",
                    "MACOS_SIGNING_CERT": "${{ secrets.MACOS_SIGNING_CERT_ACTIONS_RUNTIME }}",
                    "VAULT_URL": "${{ secrets.WIN_SIGN_AZURE_KEY_VAULT_URL_ACTIONS_RUNTIME }}",
                },
                "run": """set -Eeuo pipefail
signed=false
if [[ "$SIGNING_EVENT" == "workflow_dispatch" ]]; then
  if [[ "$SIGNING_OS" == "macos-15" && -n "${MACOS_SIGNING_CERT:-}" ]]; then signed=true; fi
  if [[ "$SIGNING_OS" == "windows-2022" && -n "${VAULT_URL:-}" ]]; then signed=true; fi
fi
if [[ "$SIGNING_OS" != "ubuntu-22.04" && "$signed" != true ]]; then
  echo "release signing credentials are required" >&2
  exit 1
fi
echo "signed=$signed" >> "$GITHUB_OUTPUT"
""",
            },
            {
                "name": "Build binary (signed)",
                "if": "${{ steps.signing.outputs.signed == 'true' }}",
                "env": signing_env,
                "run": f"{run_in_env}poetry run inv build-executable --sign --go-wrapper",
            },
            {
                "name": "Build binary (unsigned)",
                "if": "${{ steps.signing.outputs.signed != 'true' }}",
                "env": common_env,
                "run": f"{run_in_env}poetry run inv build-executable --go-wrapper",
            },
        ]

    def build_steps(self) -> list[dict]:
        raise NotImplementedError("Subclasses must implement this method")

    def upload_artifact(
        self, name: str, path: str, if_clause: str | None = None, pinned=False
    ) -> dict:
        """Helper method to create a standardized artifact upload step.

        Args:
            name: Name of the artifact
            path: Path to the files to upload
        """
        ret = {
            "name": f"Upload artifact: {path}",
            "uses": "actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02"
            if pinned
            else "actions/upload-artifact@v4",
            "with": {
                "name": name,
                "path": path,
            },
        }
        if if_clause:
            ret["if"] = if_clause
        return ret


class BaseTests(BaseWorkflow):
    require_node = False
    require_go = False
    require_build_frontend = False
    require_build_oauth2_config = False
    validate_docstrings = False

    def run_tests(self):
        return {
            "name": "Test",
            "env": {
                "GITHUB_ACTIONS_MATRIX_NAME": "${{ matrix.name }}",
                "CI_CREDENTIALS": "${{ secrets.CI_CREDENTIALS }}",
                "CI_ENDPOINT": "${{ secrets.CI_ENDPOINT }}",
                "ACTION_SERVER_TEST_ACCESS_CREDENTIALS": "${{ secrets.ACTION_SERVER_TEST_ACCESS_CREDENTIALS }}",
                "ACTION_SERVER_TEST_HOSTNAME": "${{ secrets.ACTION_SERVER_TEST_HOSTNAME }}",
            },
            "run": f"{run_in_env}inv test",
        }

    @override
    def build_steps(self) -> list[dict]:
        steps = [self.checkout_repo()] + self.setup_python() + [self.install_devutils()]

        steps.extend(self.install())

        if self.require_go:
            steps.append(self.setup_go())

        if self.require_build_frontend or self.require_node:
            steps.append(self.setup_node())

        if self.require_build_frontend:
            steps.append(self.build_frontend())

        if self.require_build_oauth2_config:
            steps.append(self.build_oauth2_config())

        run_tests = self.run_tests()
        if isinstance(run_tests, list):
            steps.extend(run_tests)
        else:
            steps.append(run_tests)

        steps.extend([self.run_lint(), self.run_typecheck(), self.run_docs()])

        if self.validate_docstrings:
            steps.append(self.run_docstrings_validation())

        return steps


class ActionServerTests(BaseTests):
    name = "Action Server Tests"
    target = "actions_runtime_tests.yml"
    project_name = "action_server"
    require_node = True
    require_go = True
    require_build_frontend = True
    require_build_oauth2_config = True

    @override
    def run_tests(self):
        return [
            # As we want to run the tests in the binary, we do the following:
            # 1. Build the binary
            # 2. Run the unit-tests (not integration) in the current environment
            # 3. Run the integration-tests in the binary
            self.build_action_server_binary(),
            self.upload_artifact(
                name="action-server-${{ matrix.os }}", path="action_server/dist/final/"
            ),
            {
                "name": "Test (not integration)",
                "env": {
                    "GITHUB_ACTIONS_MATRIX_NAME": "${{ matrix.name }}",
                    "CI_CREDENTIALS": "${{ secrets.CI_CREDENTIALS }}",
                    "CI_ENDPOINT": "${{ secrets.CI_ENDPOINT }}",
                    "ACTION_SERVER_TEST_ACCESS_CREDENTIALS": "${{ secrets.ACTION_SERVER_TEST_ACCESS_CREDENTIALS }}",
                    "ACTION_SERVER_TEST_HOSTNAME": "${{ secrets.ACTION_SERVER_TEST_HOSTNAME }}",
                },
                "run": f"{run_in_env}poetry run inv test-not-integration",
            },
            {
                "name": "Test (integration)",
                "env": {
                    "GITHUB_ACTIONS_MATRIX_NAME": "${{ matrix.name }}",
                    "CI_CREDENTIALS": "${{ secrets.CI_CREDENTIALS }}",
                    "CI_ENDPOINT": "${{ secrets.CI_ENDPOINT }}",
                    "ACTION_SERVER_TEST_ACCESS_CREDENTIALS": "${{ secrets.ACTION_SERVER_TEST_ACCESS_CREDENTIALS }}",
                    "ACTION_SERVER_TEST_HOSTNAME": "${{ secrets.ACTION_SERVER_TEST_HOSTNAME }}",
                },
                "run": f"{run_in_env}poetry run inv test-binary --jobs 0",
            },
        ]


class ActionServerPyPiRelease(BaseWorkflow):
    name = "Action Server PYPI Release"
    target = "actions_runtime_pypi_release.yml"
    project_name = "action_server"
    fail_fast = True

    @override
    def on_part(self, dep_paths):
        return {
            "on": {
                "push": {
                    "tags": ["actions-runtime-*"],
                },
                "pull_request": {
                    "branches": ["community"],
                    "paths": [
                        ".github/workflows/_gen_workflows.py",
                        ".github/workflows/actions_runtime_pypi_release.yml",
                        ".github/workflows/actions_runtime_binary_release.yml",
                        ".github/workflows/actions_runtime_manylinux_release.yml",
                        "devutils/tests/test_runtime_release_workflows.py",
                        "docs/skills/repository-operations.md",
                        "action_server/scripts/publish_verified_runtime.py",
                    ],
                },
            }
        }

    def build_sdist(self):
        return {
            "name": "Build sdist",
            "run": f"""
# Make sure that we have no binaries present when doing the build.
rm src/actions/server/bin/rcc* -f
# Wheels are built in the matrix job.
{run_in_env}poetry build -f sdist
""",
            "env": {
                "CI": True,
                "ACTION_SERVER_SKIP_DOWNLOAD_IN_BUILD": True,
            },
        }

    def upload_artifact_action_server_dist(self):
        return self.upload_artifact(
            name="action-server-dist", path="action_server/dist/*", pinned=True
        )

    def common_build_steps(self):
        steps = (
            [self.checkout_repo(pinned=True)]
            + self.setup_python(pinned=True)
            + [self.install_devutils()]
        )
        steps.extend(self.install(env={"ACTION_SERVER_SKIP_DOWNLOAD_IN_BUILD": "true"}))
        steps.append(self.setup_node(pinned=True))
        steps.append(
            {
                "name": "Check tag version",
                "run": f"{run_in_env}poetry run inv check-tag-version",
                "if": "${{ github.event_name == 'push' && !endsWith(github.ref_name, '-beta') }}",
            }
        )
        steps.extend(self.secret_scoped_build_frontend())
        steps.extend(self.secret_scoped_build_oauth2_config())
        return steps

    def secret_scoped_build_frontend(self):
        release_step = self.build_frontend()
        release_step["if"] = "github.event_name == 'push'"
        canary_step = {
            "name": "Build frontend (PR)",
            "run": release_step["run"],
            "if": "github.event_name == 'pull_request'",
            "env": {"CI": True},
        }
        return [release_step, canary_step]

    def secret_scoped_build_oauth2_config(self):
        release_step = self.build_oauth2_config()
        release_step["if"] = "github.event_name == 'push'"
        canary_step = {
            "name": "Build OAuth2 config (PR)",
            "run": release_step["run"],
            "if": "github.event_name == 'pull_request'",
        }
        return [release_step, canary_step]

    def build_sdist_steps(self):
        steps = self.common_build_steps()
        steps.append(self.build_sdist())
        steps.append(self.upload_artifact_action_server_dist())
        return steps

    def build_manylinux_wheels(self):
        CIBW_BUILD = "cp312-*macos*arm64 cp313-*macos*arm64 cp312-*manylinux*x86_64 cp313-*manylinux*x86_64 cp312-*win*amd64 cp313-*win*amd64"
        return {
            "name": "Build and clean-test wheels",
            "run": f"{run_in_env}python -m cibuildwheel --output-dir wheelhouse",
            "env": {
                "CIBW_SKIP": "pp*",
                "CIBW_BUILD": CIBW_BUILD,
                "CIBW_BUILD_VERBOSITY": 1,
                "CIBW_TEST_COMMAND": "python -m pip check && python -m actions.server version",
            },
        }

    def upload_artifact_manylinux_wheels(self):
        return self.upload_artifact(
            name="${{ runner.os }}-wheels",
            path="action_server/wheelhouse/*",
            pinned=True,
        )

    def build_wheels_steps(self):
        steps = self.common_build_steps()
        steps.append(
            self.install_devutils(additional_packages=["cibuildwheel==2.23.1"])
        )
        steps.append(
            {
                "name": "Set macOS deployment target",
                "if": "${{ matrix.name == 'macos' }}",
                "run": "echo 'MACOSX_DEPLOYMENT_TARGET=12.0' >> \"$GITHUB_ENV\"",
            }
        )
        steps.append(self.build_manylinux_wheels())
        steps.append(self.upload_artifact_manylinux_wheels())
        return steps

    def matrix_runtime_wheels(self, pyversion: str):
        matrix = self.matrix_cibuildwheel(pyversion)
        for name, row in zip(("ubuntu", "windows", "macos"), matrix["include"]):
            row["name"] = name
        return matrix

    def publish_steps(self):
        provenance = 'set -Eeuo pipefail\ngit fetch origin community:refs/remotes/origin/community\ngit merge-base --is-ancestor "$GITHUB_SHA" origin/community\ntag_version=${GITHUB_REF_NAME#actions-runtime-}\ncd action_server\npackage_version=$(uv run --no-project --python 3.12 poetry version --short)\nif [[ "$tag_version" != "$package_version" ]]; then printf \'tag version %s does not match package version %s\\n\' "$tag_version" "$package_version" >&2; exit 1; fi'
        inventory = """set -Eeuo pipefail
cd action_server
rm -rf dist/verified
mkdir -p dist/verified
find dist/downloads -type f -printf '%f\\n' | sort > /tmp/runtime-artifacts
test \"$(wc -l < /tmp/runtime-artifacts)\" -eq 7
test -z \"$(uniq -d /tmp/runtime-artifacts)\"
sdist=$(grep -E '^actions_runtime-[0-9][^/]*\\.tar\\.gz$' /tmp/runtime-artifacts)
test \"$(printf '%s\\n' \"$sdist\" | wc -l)\" -eq 1
version=${sdist#actions_runtime-}
version=${version%.tar.gz}
printf '%s\\n' \\
  \"actions_runtime-$version.tar.gz\" \\
  \"actions_runtime-$version-cp312-cp312-manylinux_2_17_x86_64.manylinux_2_5_x86_64.manylinux1_x86_64.manylinux2014_x86_64.whl\" \\
  \"actions_runtime-$version-cp313-cp313-manylinux_2_17_x86_64.manylinux_2_5_x86_64.manylinux1_x86_64.manylinux2014_x86_64.whl\" \\
  \"actions_runtime-$version-cp312-cp312-macosx_12_0_arm64.whl\" \\
  \"actions_runtime-$version-cp313-cp313-macosx_12_0_arm64.whl\" \\
  \"actions_runtime-$version-cp312-cp312-win_amd64.whl\" \\
  \"actions_runtime-$version-cp313-cp313-win_amd64.whl\" | sort > /tmp/runtime-expected
diff -u /tmp/runtime-expected /tmp/runtime-artifacts
while IFS= read -r basename; do
  source=$(find dist/downloads -type f -name \"$basename\" -print -quit)
  test -n \"$source\"
  cp -- \"$source\" dist/verified/\"$basename\"
done < /tmp/runtime-artifacts
mv dist/verified/* dist/
rmdir dist/verified
rm -rf dist/downloads
sha256sum dist/*.whl dist/*.tar.gz | sed 's#dist/##' | sort > dist/actions-runtime-manifest.sha256
"""
        return [
            self.checkout_repo(pinned=True),
            *self.setup_python(pinned=True),
            {**self.install_devutils(), "working-directory": "action_server"},
            {
                "name": "Verify merged tag provenance and version",
                "if": "github.event_name == 'push'",
                "run": provenance,
            },
            {
                "name": "Download sdist artifact",
                "uses": "actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093",
                "with": {
                    "name": "action-server-dist",
                    "path": "action_server/dist/downloads/sdist",
                },
            },
            {
                "name": "Download wheel artifacts separately",
                "uses": "actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093",
                "with": {
                    "pattern": "*-wheels",
                    "path": "action_server/dist/downloads/wheels",
                    "merge-multiple": False,
                },
            },
            {"name": "Verify exact Runtime artifact inventory", "run": inventory},
            {
                "name": "Install Twine 6.2.0",
                "run": f"{run_in_env}python -m pip install --break-system-packages twine==6.2.0",
            },
            {
                "name": "Verify Runtime artifacts",
                "run": f"{run_in_env}twine check --strict action_server/dist/*.whl action_server/dist/*.tar.gz",
            },
            {
                "name": "Canary local Runtime verifier",
                "run": f"{run_in_env}python action_server/scripts/publish_verified_runtime.py --dist-dir action_server/dist --dry-run",
            },
            self.upload_artifact(
                name="actions-runtime-dist", path="action_server/dist/*", pinned=True
            ),
            {
                "name": "Check Runtime publish credential",
                "id": "runtime-token",
                "if": "github.event_name == 'push'",
                "env": {"RUNTIME_TOKEN": "${{ secrets.PYPI_TOKEN_ACTIONS_RUNTIME }}"},
                "run": 'if [[ -n "${RUNTIME_TOKEN:-}" ]]; then echo \'enabled=true\' >> "$GITHUB_OUTPUT"; else echo \'enabled=false\' >> "$GITHUB_OUTPUT"; fi',
            },
            {
                "name": "Publish verified artifacts",
                "if": "github.event_name == 'push' && steps.runtime-token.outputs.enabled == 'true'",
                "run": f"{run_in_env}twine upload action_server/dist/*.whl action_server/dist/*.tar.gz",
                "env": {
                    "TWINE_USERNAME": "__token__",
                    "TWINE_PASSWORD": "${{ secrets[format('PYPI_TOKEN_{0}', 'ACTIONS_RUNTIME')] }}",
                },
            },
        ]

    @override
    def jobs_part(self):
        return {
            "jobs": {
                "build-sdist": {
                    "runs-on": "${{ matrix.os }}",
                    "strategy": {
                        "matrix": self.matrix_ubuntu(self.minimum_python_version)
                    },
                    "steps": self.build_sdist_steps(),
                },
                "build-wheels": {
                    "runs-on": "${{ matrix.os }}",
                    "strategy": {
                        "fail-fast": self.fail_fast,
                        "matrix": self.matrix_runtime_wheels(
                            self.minimum_python_version
                        ),
                    },
                    "steps": self.build_wheels_steps(),
                },
                "publish": {
                    "needs": ["build-sdist", "build-wheels"],
                    "permissions": {"contents": "read"},
                    "environment": "pypi",
                    "runs-on": UBUNTU_VERSION,
                    "defaults": {"run": {"working-directory": "."}},
                    "strategy": {"matrix": {"python": [self.minimum_python_version]}},
                    "steps": self.publish_steps(),
                },
            }
        }


class ActionServerBinaryRelease(BaseWorkflow):
    name = "Action Server BINARY Release"
    target = "actions_runtime_binary_release.yml"
    project_name = "action_server"
    fail_fast = True

    @override
    def on_part(self, dep_paths):
        return {
            "on": {
                "push": {
                    "tags": ["actions-runtime-*"],
                    "branches": ["*-beta"],
                },
            }
        }

    @override
    def runs_on_and_strategy_part(self):
        return {
            "runs-on": "${{ matrix.os }}",
            "strategy": {
                "fail-fast": self.fail_fast,
                "matrix": self.matrix_binary_release(self.minimum_python_version),
            },
        }

    def upload_artifact_with_asset_path(self):
        return self.upload_artifact(
            name="action-server-${{ matrix.os }}",
            path="action_server/dist/final/",
            pinned=True,
        )

    def set_version_on_ubuntu(self):
        return {
            "name": "Set version",
            "run": f"""
{run_in_env}poetry version --short > version.txt
VERSION=$(cat version.txt)

echo "Version: $VERSION"
echo "version=$VERSION" >> "$GITHUB_OUTPUT"
""",
            "id": "set_version",
            "if": "${{ matrix.os == '" + UBUNTU_VERSION + "' }}",
        }

    def upload_artifact_action_server_version_on_ubuntu(self):
        # Having a separate artifact for version.txt helps downstream workflows
        return self.upload_artifact(
            name="action-server-version",
            path="action_server/version.txt",
            if_clause="${{ matrix.os == '" + UBUNTU_VERSION + "' }}",
            pinned=True,
        )

    def build_steps(self) -> list[dict]:
        steps = (
            [self.checkout_repo(pinned=True)]
            + self.setup_python(pinned=True)
            + [self.install_devutils()]
        )

        steps.extend(self.install())

        steps.append(self.setup_node(pinned=True))
        steps.append(self.setup_go(pinned=True))

        steps.append(self.check_tag_version())
        steps.append(self.build_frontend())
        steps.append(self.build_oauth2_config())

        steps.append(self.set_version_on_ubuntu())
        steps.extend(self.build_action_server_binary_cross_platform())
        steps.append(self.upload_artifact_with_asset_path())
        steps.append(self.upload_artifact_action_server_version_on_ubuntu())

        return steps

    def build_job_part(self):
        build = super().build_job_part()
        build["outputs"] = {"version": "${{ steps.set_version.outputs.version }}"}
        return build

    @override
    def jobs_part(self):
        jobs = super().jobs_part()
        jobs["jobs"]["deploy-s3"] = self.deploy_s3_job_part()
        jobs["jobs"].update(self.trigger_brew_workflow_job_part())
        jobs["jobs"].update(self.release_job_part())
        return jobs

    def trigger_brew_workflow_job_part(self):
        return {
            "trigger-brew-workflow": {
                "needs": ["build", "deploy-s3"],
                "defaults": {"run": {"working-directory": "."}},
                "if": "${{ needs.deploy-s3.outputs.is_beta == 'false' }}",
                "runs-on": UBUNTU_VERSION,
                "steps": [
                    {
                        "name": "Wait for Downloads S3 Bucket to have the right content",
                        "timeout-minutes": 5,
                        "run": """
VERSION_URL="https://cdn.sema4.ai/action-server/releases/latest/version.txt"
EXPECTED_VERSION=${{ needs.build.outputs.version }}
echo "Expected version: $EXPECTED_VERSION"
while true; do
  DOWNLOADED_VERSION=$(curl -sS $VERSION_URL)
  echo "Downloaded version: $DOWNLOADED_VERSION"
  echo "Expected version: $EXPECTED_VERSION"
    if [ "$DOWNLOADED_VERSION" = "$EXPECTED_VERSION" ]; then
      echo "Versions match."
      break
    else
      echo "Versions do not match. Retrying in 30 seconds."
    fi
    sleep 30
    done
""",
                    },
                    {
                        "name": "Trigger Brew Deploy Workflow",
                        "run": """curl -X POST \
           -H "Authorization: token ${{ secrets.GH_PAT_GHA_TO_ANOTHER_REPO }}" \
           -H "Accept: application/vnd.github.v3+json" \
           https://api.github.com/repos/sema4ai/homebrew-tools/actions/workflows/publish.yml/dispatches \
           -d '{"ref":"main","inputs":{"version":"${{ needs.build.outputs.version }}"}}'""",
                    },
                ],
            },
        }

    def release_job_part(self):
        return {
            "release": {
                "if": "${{ needs.deploy-s3.outputs.is_beta == 'false' }}",
                "permissions": {"contents": "write"},
                "needs": ["deploy-s3", "trigger-brew-workflow"],
                "defaults": {"run": {"working-directory": "."}},
                "runs-on": UBUNTU_VERSION,
                "steps": [
                    {
                        "uses": "actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09"
                    },
                    {
                        "name": "Create GitHub release",
                        "uses": "Roang-zero1/github-create-release-action@57eb9bdce7a964e48788b9e78b5ac766cb684803",
                        "with": {
                            "release_title": "${{ github.ref_name }}",
                            "changelog_file": "action_server/docs/CHANGELOG.md",
                            "release_text": "Binaries available as assets. Run `action-server -h` for usage instructions.",
                        },
                        "env": {"GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"},
                    },
                    {
                        "uses": "actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093",
                        "with": {
                            "name": "action-server-windows-2022",
                            "path": "windows64/",
                        },
                    },
                    {
                        "uses": "actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093",
                        "with": {
                            "name": "action-server-macos-15",
                            "path": "macos-arm64/",
                        },
                    },
                    {
                        "uses": "actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093",
                        "with": {
                            "name": f"action-server-{UBUNTU_VERSION}",
                            "path": "linux64/",
                        },
                    },
                    {
                        "name": "Print contents",
                        "run": """
          pwd
          ls -l
          echo "Windows64:"
          cd windows64
          ls -l
          cd ../macos-arm64
          echo "MacOS-arm64:"
          ls -l
          cd ../linux64
          echo "Linux64:"
          ls -l
          cd ..
          echo "GitHub ref: ${{ github.ref }}"
          """,
                    },
                    {
                        "name": "Upload Linux binary",
                        "uses": "svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd",  # v2
                        "with": {
                            "repo_token": "${{ secrets.GITHUB_TOKEN }}",
                            "file": "./linux64/action-server",
                            "asset_name": "${{ github.ref_name }}-linux64",
                            "tag": "${{ github.ref }}",
                            "overwrite": True,
                        },
                    },
                    {
                        "name": "Upload MacOS arm binary",
                        "uses": "svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd",  # v2
                        "with": {
                            "repo_token": "${{ secrets.GITHUB_TOKEN }}",
                            "file": "./macos-arm64/action-server",
                            "asset_name": "${{ github.ref_name }}-macos-arm64",
                            "tag": "${{ github.ref }}",
                            "overwrite": True,
                        },
                    },
                    {
                        "name": "Upload Windows binary",
                        "uses": "svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd",  # v2
                        "with": {
                            "repo_token": "${{ secrets.GITHUB_TOKEN }}",
                            "file": "./windows64/action-server.exe",
                            "asset_name": "${{ github.ref_name }}-windows64.exe",
                            "tag": "${{ github.ref }}",
                            "overwrite": True,
                        },
                    },
                ],
            }
        }

    def deploy_s3_job_part(self):
        return {
            "permissions": {
                "id-token": "write",  # required by AWS aws-actions/configure-aws-credentials
                "contents": "read",
            },
            "needs": ["build"],
            "defaults": {
                "run": {
                    "working-directory": "./action_server",
                },
            },
            "runs-on": UBUNTU_VERSION,
            "outputs": {"is_beta": "${{ steps.check_beta.outputs.is_beta }}"},
            "steps": self.deploy_s3_job_steps(),
        }

    def download_artifacts(self):
        # It'll generate something as (for all the OSes we require):
        #   - uses: actions/download-artifact@v4
        #     with:
        #       name: action-server-windows-2022
        #       path: action_server/build/windows64/

        ret = []
        for os, path in [
            ("windows-2022", "windows64"),
            ("macos-15", "macos-arm64"),
            (UBUNTU_VERSION, "linux64"),
        ]:
            ret.append(
                {
                    "name": f"Download artifact {os}",
                    "uses": "actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093",
                    "with": {
                        "name": f"action-server-{os}",
                        "path": f"action_server/build/{path}/",
                    },
                }
            )

        ret.append(
            {
                "name": "Download artifact version",
                "uses": "actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093",
                "with": {
                    "name": "action-server-version",
                    "path": "action_server/build/",
                },
            }
        )
        return ret

    def deploy_s3_job_steps(self):
        steps = []
        steps.append(self.checkout_repo(pinned=True))
        steps.append(self.is_beta_in_steps())
        steps.extend(self.download_artifacts())
        steps.extend(self.upload_to_s3())
        return steps

    def upload_to_s3(self):
        ret = []

        ret.append(
            {
                "name": "Put files in s3-drop",
                "run": """
ls -l
pwd
ls -l build
mkdir s3-drop
mv build/version.txt s3-drop/
mv build/macos-arm64 s3-drop/
mv build/linux64 s3-drop/
mv build/windows64 s3-drop/
ls -l s3-drop/
ver=$(cat s3-drop/version.txt)
echo "actionServerVersion=${ver}" >> "$GITHUB_ENV"
""",
            }
        )

        ret.append(
            self.upload_artifact(
                name="action-server-artifacts-for-s3-${{ env.actionServerVersion }}",
                path="action_server/s3-drop",
                pinned=True,
            )
        )

        ret.append(
            {
                "name": "Configure AWS credentials Dropbox bucket",
                "uses": "aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df",
                "with": {
                    "aws-region": "eu-west-1",
                    "role-to-assume": "arn:aws:iam::710450854638:role/github-action-robocorp-action-server",
                },
            }
        )

        ret.append(
            {
                "name": "AWS S3 copies",
                "run": """
if [ "${{ steps.check_beta.outputs.is_beta }}" = "false" ]; then
  echo "Normal release, aws sync to drop-box, full pipeline"
  aws s3 sync s3-drop s3://robocorp-action-server-build-drop-box
else
  echo "BETA RELEASE, only copy the executable for testing"
  S3_BASE_URL="s3://downloads.robocorp.com/action-server/beta"
  aws s3 cp s3-drop/version.txt $S3_BASE_URL/version.txt --cache-control max-age=120 --content-type "text/plain"
  aws s3 cp s3-drop/windows64/action-server.exe $S3_BASE_URL/windows64/action-server.exe --cache-control max-age=120 --content-type "application/octet-stream"
  aws s3 cp s3-drop/macos-arm64/action-server $S3_BASE_URL/macos-arm64/action-server --cache-control max-age=120 --content-type "application/octet-stream"
  aws s3 cp s3-drop/linux64/action-server $S3_BASE_URL/linux64/action-server --cache-control max-age=120 --content-type "application/octet-stream"
fi
""",
            }
        )

        return ret


class ActionServerRuntimeRecovery(BaseWorkflow):
    name = "Action Server Runtime Recovery"
    target = "actions_runtime_recovery.yml"
    project_name = "action_server"
    recovery_run_in_env = "uv run --no-project --python 3.12 "
    pypi_artifacts = {
        "action-server-dist": (
            9202638277,
            "848656",
            "sha256:e68002161c7c05c7558339816733e56fc953fd8fe1bbf02f99f1f70c4a575072",
        ),
        "Linux-wheels": (
            9202661215,
            "26180637",
            "sha256:e63ebadb20107adba8a6c76489105339337c1406db96ff328161dda9baf0c34e",
        ),
        "macOS-wheels": (
            9202659672,
            "24523055",
            "sha256:5bba95082475ec10810edc3cf51a7a905ac135fd3fc58246be0f0244b53e281e",
        ),
        "Windows-wheels": (
            9202679653,
            "21134688",
            "sha256:24daf1623d5b770b877b6e6d0b590b90b7b6d75f258b39cc1a20e30ca584f359",
        ),
    }

    def __init__(self):
        super().__init__()
        self.full["permissions"] = {"contents": "read", "actions": "read"}
        self.full["run-name"] = (
            "Runtime recovery: ${{ inputs.release_ref }} @ ${{ inputs.release_sha }}"
        )

    @override
    def on_part(self, dep_paths):
        return {
            "on": {
                "workflow_dispatch": {
                    "inputs": {
                        "release_ref": {
                            "description": "Immutable actions-runtime release tag",
                            "required": True,
                            "type": "string",
                        },
                        "release_sha": {
                            "description": "Full 40-hex commit resolved by the release tag",
                            "required": True,
                            "type": "string",
                        },
                        "pypi_source_run_id": {
                            "description": "Failed canonical PyPI run whose successful component artifacts are reused",
                            "required": False,
                            "default": "31755673247",
                            "type": "string",
                        },
                        "pypi_source_workflow_id": {
                            "description": "Canonical Runtime PyPI workflow database ID",
                            "required": False,
                            "default": "333870965",
                            "type": "string",
                        },
                    }
                }
            }
        }

    @override
    def defaults_part(self):
        return {"defaults": {"run": {"working-directory": "."}}}

    def recovery_install_devutils(self):
        step = self.install_devutils()
        step["run"] = step["run"].replace(run_in_env, self.recovery_run_in_env)
        return step

    def checkout_recovery_code(self):
        return {
            "name": "Checkout merged recovery code",
            "uses": "actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09",
            "with": {
                "ref": "${{ github.workflow_sha }}",
                "path": "recovery-code",
                "fetch-depth": 0,
                "persist-credentials": False,
            },
        }

    def checkout_release_source(self):
        return {
            "name": "Checkout immutable release source",
            "uses": "actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09",
            "with": {
                "ref": "${{ inputs.release_sha }}",
                "path": "release-source",
                "fetch-depth": 0,
                "persist-credentials": False,
            },
        }

    def recovery_source_guard(self):
        return {
            "name": "Verify immutable tag, ancestry, and package version",
            "working-directory": ".",
            "env": {
                "RELEASE_REF": "${{ inputs.release_ref }}",
                "RELEASE_SHA": "${{ inputs.release_sha }}",
            },
            "run": r"""set -Eeuo pipefail
[[ "$RELEASE_REF" =~ ^actions-runtime-[0-9]+\.[0-9]+\.[0-9]+$ ]]
[[ "$RELEASE_SHA" =~ ^[0-9a-f]{40}$ ]]
test "$(git -C release-source rev-parse HEAD)" = "$RELEASE_SHA"
git -C release-source fetch --no-tags origin "refs/tags/$RELEASE_REF:refs/tags/$RELEASE_REF" "refs/heads/community:refs/remotes/origin/community"
test "$(git -C release-source rev-parse "refs/tags/$RELEASE_REF^{commit}")" = "$RELEASE_SHA"
git -C release-source merge-base --is-ancestor "$RELEASE_SHA" refs/remotes/origin/community
""",
        }

    def recovery_source_version_guard(self):
        return {
            "name": "Verify immutable Runtime source version",
            "env": {"RELEASE_REF": "${{ inputs.release_ref }}"},
            "working-directory": "release-source/action_server",
            "run": """set -Eeuo pipefail
tag_version="${RELEASE_REF#actions-runtime-}"
package_version=$(uv run --no-project --python 3.12 poetry version --short)
test "$package_version" = "$tag_version"
""",
        }

    def recovery_admission_guard(self):
        return {
            "name": "Admit only merged community recovery code",
            "env": {
                "WORKFLOW_REF": "${{ github.workflow_ref }}",
                "WORKFLOW_SHA": "${{ github.workflow_sha }}",
                "REPOSITORY": "${{ github.repository }}",
            },
            "run": r"""set -Eeuo pipefail
test "$REPOSITORY" = "joshyorko/actions"
test "$WORKFLOW_REF" = "joshyorko/actions/.github/workflows/actions_runtime_recovery.yml@refs/heads/community"
[[ "$WORKFLOW_SHA" =~ ^[0-9a-f]{40}$ ]]
git -C recovery-code fetch --no-tags origin "refs/heads/community:refs/remotes/origin/community"
test "$(git -C recovery-code rev-parse HEAD)" = "$WORKFLOW_SHA"
test "$(git -C recovery-code rev-parse refs/remotes/origin/community)" = "$WORKFLOW_SHA"
""",
        }

    def recovery_checkouts_and_guard(self):
        steps = [
            self.checkout_recovery_code(),
            self.recovery_admission_guard(),
            self.checkout_release_source(),
        ]
        steps.append(self.recovery_source_guard())
        steps.extend(self.setup_python(pinned=True))
        steps.append(
            {
                **self.recovery_install_devutils(),
                "working-directory": "release-source/action_server",
            }
        )
        steps.append(self.recovery_source_version_guard())
        return steps

    def validate_job_part(self):
        steps = self.recovery_checkouts_and_guard()
        return {
            "runs-on": UBUNTU_VERSION,
            "permissions": {"contents": "read"},
            "defaults": {"run": {"working-directory": "."}},
            "steps": steps,
        }

    def pypi_source_validation(self):
        return {
            "name": "Validate retained failed-run PyPI components",
            "env": {
                "PYPI_SOURCE_RUN_ID": "${{ inputs.pypi_source_run_id }}",
                "PYPI_SOURCE_WORKFLOW_ID": "${{ inputs.pypi_source_workflow_id }}",
                "RELEASE_REF": "${{ inputs.release_ref }}",
                "RELEASE_SHA": "${{ inputs.release_sha }}",
                "GH_TOKEN": "${{ github.token }}",
            },
            "run": """set -Eeuo pipefail
test -n "$PYPI_SOURCE_RUN_ID"
test -n "$PYPI_SOURCE_WORKFLOW_ID"
workflow_json=$(gh api "repos/$GITHUB_REPOSITORY/actions/workflows/actions_runtime_pypi_release.yml")
test "$(jq -r '.id' <<<"$workflow_json")" = "$PYPI_SOURCE_WORKFLOW_ID"
test "$(jq -r '.path' <<<"$workflow_json")" = ".github/workflows/actions_runtime_pypi_release.yml"
test "$(jq -r '.state' <<<"$workflow_json")" = "active"
run_json=$(gh api "repos/$GITHUB_REPOSITORY/actions/runs/$PYPI_SOURCE_RUN_ID")
jq -e --arg sha "$RELEASE_SHA" --arg ref "$RELEASE_REF" --arg workflow "$PYPI_SOURCE_WORKFLOW_ID" --arg run "$PYPI_SOURCE_RUN_ID" --arg repo "$GITHUB_REPOSITORY" '
  .id == ($run | tonumber)
  and .run_attempt == 1
  and .workflow_id == ($workflow | tonumber)
  and .path == ".github/workflows/actions_runtime_pypi_release.yml"
  and .head_sha == $sha
  and .head_branch == $ref
  and .event == "push"
  and .conclusion == "failure"
  and .repository.full_name == $repo
  and .head_repository.full_name == $repo
' <<<"$run_json"
jobs_json=$(gh api "repos/$GITHUB_REPOSITORY/actions/runs/$PYPI_SOURCE_RUN_ID/jobs?per_page=100")
jq -e --argjson required '["build-sdist (ubuntu-py3.12)", "build-wheels (macos-15)", "build-wheels (ubuntu-22.04)", "build-wheels (windows-2022)"]' '
  [.jobs[] | select(.name as $name | ($required | index($name)) != null)] as $selected
  | ($selected | length == 4)
  and (($selected | map(.name) | sort) == ($required | sort))
  and ($selected | all(.[]; .status == "completed" and .conclusion == "success"))
  and ([.jobs[] | select(.name == "publish (3.12)")] | length == 1)
  and ([.jobs[] | select(.name == "publish (3.12)")][0].conclusion == "failure")
  and ([.jobs[] | select(.name == "publish (3.12)")][0].steps[] | select(.name == "Verify merged tag provenance and version") | .conclusion) == ["failure"]
' <<<"$jobs_json"
artifacts_json=$(gh api "repos/$GITHUB_REPOSITORY/actions/runs/$PYPI_SOURCE_RUN_ID/artifacts?per_page=100")
jq -e --arg repo "$GITHUB_REPOSITORY" '
  [.artifacts[] | select(.workflow_run.id == 31755673247)] as $all
  | ($all | length == 4)
  and ($all | all(.expired == false))
  and ($all | map({id,name,size_in_bytes,digest}) | sort_by(.name) == [
    {id:9202638277,name:"action-server-dist",size_in_bytes:848656,digest:"sha256:e68002161c7c05c7558339816733e56fc953fd8fe1bbf02f99f1f70c4a575072"},
    {id:9202661215,name:"Linux-wheels",size_in_bytes:26180637,digest:"sha256:e63ebadb20107adba8a6c76489105339337c1406db96ff328161dda9baf0c34e"},
    {id:9202659672,name:"macOS-wheels",size_in_bytes:24523055,digest:"sha256:5bba95082475ec10810edc3cf51a7a905ac135fd3fc58246be0f0244b53e281e"},
    {id:9202679653,name:"Windows-wheels",size_in_bytes:21134688,digest:"sha256:24daf1623d5b770b877b6e6d0b590b90b7b6d75f258b39cc1a20e30ca584f359"}
  ])
' <<<"$artifacts_json"
""",
        }

    def pypi_download_steps(self):
        downloads = []
        for name, path in (
            ("action-server-dist", "pypi-components/sdist"),
            ("Linux-wheels", "pypi-components/linux"),
            ("macOS-wheels", "pypi-components/macos"),
            ("Windows-wheels", "pypi-components/windows"),
        ):
            artifact_id, _, digest = self.pypi_artifacts[name]
            downloads.append(
                {
                    "name": f"Download retained {name}",
                    "env": {
                        "ARTIFACT_ID": str(artifact_id),
                        "DESTINATION": path,
                        "GH_TOKEN": "${{ github.token }}",
                    },
                    "run": f'''set -Eeuo pipefail
mkdir -p "$DESTINATION"
gh api "repos/$GITHUB_REPOSITORY/actions/artifacts/$ARTIFACT_ID/zip" > /tmp/runtime-artifact.zip
test "$(sha256sum /tmp/runtime-artifact.zip | cut -d' ' -f1)" = "{digest.split(':', 1)[1]}"
DESTINATION="$DESTINATION" python - <<'PY'
import os
import stat
import zipfile
from pathlib import PurePosixPath

destination = os.environ["DESTINATION"]
root = os.path.realpath(destination)
with zipfile.ZipFile("/tmp/runtime-artifact.zip") as source:
    for member in source.infolist():
        path = PurePosixPath(member.filename)
        if path.is_absolute() or ".." in path.parts or "\\x00" in member.filename:
            raise SystemExit(f"unsafe archive member: {{member.filename!r}}")
        mode = (member.external_attr >> 16) & 0o177777
        if mode and stat.S_IFMT(mode) not in (0, stat.S_IFDIR, stat.S_IFREG):
            raise SystemExit(f"unsafe archive link or special member: {{member.filename!r}}")
        target = os.path.realpath(os.path.join(destination, *path.parts))
        if os.path.commonpath((root, target)) != root:
            raise SystemExit(f"archive member escapes destination: {{member.filename!r}}")
        if member.is_dir():
            os.makedirs(target, exist_ok=True)
            continue
        os.makedirs(os.path.dirname(target), exist_ok=True)
        with source.open(member) as input_file, open(target, "xb") as output_file:
            output_file.write(input_file.read())
PY
''',
                }
            )
        return downloads

    def pypi_recovery_job_part(self):
        steps = self.recovery_checkouts_and_guard()
        steps.extend(
            [
                self.pypi_source_validation(),
                *self.pypi_download_steps(),
                {
                    "name": "Combine and verify exact Runtime artifacts",
                    "run": self.recovery_run_in_env
                    + "python recovery-code/action_server/scripts/publish_verified_runtime.py --download-root pypi-components --dry-run",
                },
                {
                    "name": "Install Twine 6.2.0",
                    "run": self.recovery_run_in_env
                    + "python -m pip install --break-system-packages twine==6.2.0",
                },
                {
                    "name": "Verify Runtime artifacts",
                    "run": self.recovery_run_in_env
                    + "twine check --strict actions-runtime-dist/*.whl actions-runtime-dist/*.tar.gz",
                },
                {
                    "name": "Clean-install Runtime and run checks",
                    "run": """set -Eeuo pipefail
rm -rf /tmp/actions-runtime-recovery-venv
uv venv --python 3.12 /tmp/actions-runtime-recovery-venv
linux_wheel=$(find actions-runtime-dist -type f -name '*-cp312-cp312-manylinux*.whl' -print)
test "$(printf '%s\\n' "$linux_wheel" | sed '/^$/d' | wc -l)" -eq 1
uv pip install --python /tmp/actions-runtime-recovery-venv/bin/python "$linux_wheel"
/tmp/actions-runtime-recovery-venv/bin/python -m pip check
/tmp/actions-runtime-recovery-venv/bin/python -m actions.server version
""",
                },
                self.upload_artifact(
                    name="actions-runtime-dist",
                    path="actions-runtime-dist/*",
                    pinned=True,
                ),
            ]
        )
        return {
            "needs": ["validate"],
            "if": "${{ needs.validate.result == 'success' }}",
            "runs-on": UBUNTU_VERSION,
            "permissions": {"contents": "read", "actions": "read"},
            "defaults": {"run": {"working-directory": "."}},
            "steps": steps,
        }

    def binary_recovery_build_steps(self):
        steps = self.recovery_checkouts_and_guard()
        build_frontend = self.build_frontend()
        build_oauth2_config = self.build_oauth2_config()
        steps.extend(
            [
                {
                    "name": "Install immutable Runtime source",
                    "run": self.recovery_run_in_env + "inv install",
                    "working-directory": "release-source/action_server",
                },
                self.setup_node(pinned=True),
                {
                    **self.setup_go(pinned=True),
                    "with": {
                        **self.setup_go(pinned=True)["with"],
                        "cache-dependency-path": "release-source/action_server/go-wrapper/go.sum",
                    },
                },
                {
                    "name": "Build frontend from immutable source",
                    "run": build_frontend["run"],
                    "env": build_frontend["env"],
                    "working-directory": "release-source/action_server",
                },
                {
                    "name": "Build OAuth2 config from immutable source",
                    "run": build_oauth2_config["run"],
                    "env": build_oauth2_config["env"],
                    "working-directory": "release-source/action_server",
                },
                {
                    "name": "Verify immutable Runtime source version",
                    "env": {"RELEASE_REF": "${{ inputs.release_ref }}"},
                    "run": """set -Eeuo pipefail
tag_version="${RELEASE_REF#actions-runtime-}"
package_version=$(uv run --no-project --python 3.12 poetry version --short)
test "$package_version" = "$tag_version"
""",
                    "working-directory": "release-source/action_server",
                },
                *self.build_action_server_binary_cross_platform(
                    ref_name="${{ inputs.release_ref }}"
                ),
                self.upload_artifact(
                    name="actions-runtime-binary-${{ matrix.name }}",
                    path="release-source/action_server/dist/final/*",
                    pinned=True,
                ),
            ]
        )
        return steps

    def binary_release_normalize(self):
        return {
            "name": "Validate exact binary set",
            "env": {"RELEASE_REF": "${{ inputs.release_ref }}"},
            "run": """set -Eeuo pipefail
rm -rf release-assets
mkdir -p release-assets
test "$(find binaries/linux -type f | wc -l)" -eq 1
test "$(find binaries/macos -type f | wc -l)" -eq 1
test "$(find binaries/windows -type f | wc -l)" -eq 1
test -s binaries/linux/action-server
test -s binaries/macos/action-server
test -s binaries/windows/action-server.exe
cp binaries/linux/action-server "release-assets/${RELEASE_REF}-linux64"
cp binaries/macos/action-server "release-assets/${RELEASE_REF}-macos-arm64"
cp binaries/windows/action-server.exe "release-assets/${RELEASE_REF}-windows64.exe"
find release-assets -maxdepth 1 -type f -printf '%f\\n' | sort > /tmp/runtime-binary-assets
printf '%s\\n' "${RELEASE_REF}-linux64" "${RELEASE_REF}-macos-arm64" "${RELEASE_REF}-windows64.exe" | sort > /tmp/runtime-binary-expected
diff -u /tmp/runtime-binary-expected /tmp/runtime-binary-assets
test "$(wc -l < /tmp/runtime-binary-assets)" -eq 3
test -z "$(uniq -d /tmp/runtime-binary-assets)"
""",
        }

    def binary_release_publish(self):
        return {
            "name": "Create or update the complete GitHub release",
            "env": {
                "RELEASE_REF": "${{ inputs.release_ref }}",
                "RELEASE_SHA": "${{ inputs.release_sha }}",
                "GH_TOKEN": "${{ github.token }}",
            },
            "run": """set -Eeuo pipefail
manifest=$(mktemp)
sha256sum release-assets/* | sed 's#release-assets/##' | sort > "$manifest"
expected=$(jq -Rn '[inputs | split("  ") | {name:.[1],digest:("sha256:" + .[0])}]' < "$manifest")
release_json=""
if release_json=$(gh api "repos/$GITHUB_REPOSITORY/releases/tags/$RELEASE_REF"); then
  test "$(jq -r '.tag_name' <<<"$release_json")" = "$RELEASE_REF"
  test "$(jq -r '.target_commitish' <<<"$release_json")" = "$RELEASE_SHA"
  test "$(jq -r '.draft' <<<"$release_json")" = "true"
  jq -e --argjson expected "$expected" '([.assets[].name] - [$expected[].name] | length == 0) and ([.assets[].name] | unique | length == length)' <<<"$release_json"
  while read -r digest name; do
    existing_digest=$(jq -r --arg name "$name" '.assets[] | select(.name == $name) | .digest' <<<"$release_json")
    if [ "$existing_digest" = "null" ]; then
      gh release upload "$RELEASE_REF" "release-assets/$name"
    else
      test "$existing_digest" = "sha256:$digest"
    fi
  done < "$manifest"
else
  gh release create "$RELEASE_REF" --draft --verify-tag --target "$RELEASE_SHA" --title "$RELEASE_REF" --notes "Runtime binaries recovered from immutable $RELEASE_REF at $RELEASE_SHA."
  gh release upload "$RELEASE_REF" release-assets/*
fi
release_json=$(gh api "repos/$GITHUB_REPOSITORY/releases/tags/$RELEASE_REF")
test "$(jq -r '.tag_name' <<<"$release_json")" = "$RELEASE_REF"
test "$(jq -r '.target_commitish' <<<"$release_json")" = "$RELEASE_SHA"
test "$(jq -r '.draft' <<<"$release_json")" = "true"
expected_names=$(awk '{print $2}' "$manifest" | sort)
actual_names=$(jq -r '.assets[].name' <<<"$release_json" | sort)
test "$actual_names" = "$expected_names"
jq -e --argjson expected "$expected" '([.assets[] | {name,digest}] | sort_by(.name)) == ($expected | sort_by(.name))' <<<"$release_json"
gh release edit "$RELEASE_REF" --draft=false
""",
        }

    def binary_recovery_release_steps(self):
        steps = self.recovery_checkouts_and_guard()
        for name, path in (
            ("linux", "binaries/linux"),
            ("macos", "binaries/macos"),
            ("windows", "binaries/windows"),
        ):
            steps.append(
                {
                    "name": f"Download immutable {name} binary",
                    "uses": "actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093",
                    "with": {
                        "name": f"actions-runtime-binary-{name}",
                        "path": path,
                    },
                }
            )
        steps.extend([self.binary_release_normalize(), self.binary_release_publish()])
        return steps

    @override
    def jobs_part(self):
        return {
            "jobs": {
                "validate": self.validate_job_part(),
                "pypi-recovery": self.pypi_recovery_job_part(),
                "binary-build": {
                    "needs": ["validate"],
                    "if": "${{ needs.validate.result == 'success' }}",
                    "runs-on": "${{ matrix.os }}",
                    "permissions": {"contents": "read"},
                    "defaults": {
                        "run": {"working-directory": "release-source/action_server"}
                    },
                    "strategy": {
                        "fail-fast": False,
                        "matrix": {
                            "include": [
                                {
                                    "os": UBUNTU_VERSION,
                                    "name": "linux",
                                    "python": "3.12",
                                },
                                {"os": "macos-15", "name": "macos", "python": "3.12"},
                                {
                                    "os": "windows-2022",
                                    "name": "windows",
                                    "python": "3.12",
                                },
                            ]
                        },
                    },
                    "steps": self.binary_recovery_build_steps(),
                },
                "binary-release": {
                    "needs": ["validate", "binary-build"],
                    "if": "${{ needs.binary-build.result == 'success' }}",
                    "runs-on": UBUNTU_VERSION,
                    "permissions": {"contents": "write"},
                    "defaults": {"run": {"working-directory": "."}},
                    "steps": self.binary_recovery_release_steps(),
                },
            }
        }


class ActionsTests(BaseTests):
    name = "Actions Core Tests"
    target = "actions_core_tests.yml"
    project_name = "actions"
    require_node = True

    @override
    def on_part(self, dep_paths):
        return {
            "on": {
                "push": {
                    "branches": ["community", "wip"],
                    "paths": dep_paths[:],
                },
                "pull_request": {
                    "branches": ["community"],
                    "paths": dep_paths[:],
                },
            }
        }


class HttpHelperTests(BaseTests):
    name = "HTTP Helper Tests"
    target = "http_helper_tests.yml"
    project_name = "actions-http-helper"


TARGETS = [
    ActionServerTests(),
    ActionsTests(),
    HttpHelperTests(),
    ActionServerPyPiRelease(),
    ActionServerBinaryRelease(),
    ActionServerRuntimeRecovery(),
]


def main():
    for t in TARGETS:
        t.generate()


def generate_dependabot_config():
    """
    We want to generate a dependabot yaml that's roughly as what's below, but
    we want to define `directories` instead of `directory` where the directories
    has the paths that have the files that need to be targeted.

    For:
    - "gomod" this is any file with a `go.mod` file
    - "pip" this is any file with a `pyproject.toml` file.
    - "github-actions" this is any file with a `workflow` file.
    - "npm" this is any file with a `package.json` file.

    Template yaml is below (note: in the code we must actually create a python dict and then dump it as yaml)

    # See: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

    --- Template yaml ---
    version: 2
    updates:
    - package-ecosystem: "gomod"
        directory: "/"
        schedule:
        interval: "daily" # Options: "daily", "weekly", "monthly"
        allow:
        - dependency-type: "all" # Allows updates for all types of dependencies (direct and indirect)
        # Disable all pull requests (we just want notifications)
        open-pull-requests-limit: 0

    # Enable version updates for GitHub Actions
    - package-ecosystem: "github-actions"
        # Workflow files stored in the default location of `.github/workflows`
        # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
        directory: "/"
        schedule:
        interval: "daily"
        # Disable all pull requests (we just want notifications)
        open-pull-requests-limit: 0

    - package-ecosystem: "pip"
        directory: "/"
        schedule:
        interval: "daily" # Options: "daily", "weekly", "monthly"
        allow:
        - dependency-type: "all" # Allows updates for all types of dependencies (direct and indirect)
        commit-message:
        prefix: "deps" # Prefix to add to the commit message
        # Disable all pull requests (we just want notifications)
        open-pull-requests-limit: 0

    # Enable version updates for npm
    - package-ecosystem: "npm"
        # Look for `package.json` and `lock` files in the `root` directory
        directory: "/"
        schedule:
        interval: "daily"
        # Disable all pull requests (we just want notifications)
        open-pull-requests-limit: 0
    """
    """Generate dependabot.yml configuration based on repository structure."""
    from pathlib import Path

    root = CURDIR.parent.parent

    # Find all relevant files
    go_mod_dirs = {str(f.parent.relative_to(root)) for f in root.rglob("go.mod")}
    pyproject_dirs = {
        str(f.parent.relative_to(root))
        for f in root.rglob("pyproject.toml")
        if (
            "/tests/" not in f.as_posix()
            and "/.venv/" not in f.as_posix()
            and "/node_modules/" not in f.as_posix()
        )
    }
    package_json_dirs = {
        str(f.parent.relative_to(root))
        for f in root.rglob("package.json")
        if "node_modules" not in str(f)
    }

    # GitHub Actions is always in .github/workflows
    github_actions_dirs = {"/"}  # Root directory contains .github/workflows

    # Base configuration
    config = {"version": 2, "updates": []}

    # Helper to create ecosystem config
    def create_ecosystem_config(ecosystem, directories):
        directories = sorted(
            [
                f"{Path(directory).as_posix()}" if directory != "/" else "/"
                for directory in directories
            ]
        )
        configs = [
            {
                "package-ecosystem": ecosystem,
                "directories": directories,
                "schedule": {"interval": "daily"},
                "open-pull-requests-limit": 0,  # Only notifications, no PRs
                "allow": [{"dependency-type": "all"}],
            }
        ]

        return configs

    # Add configurations for each ecosystem
    if go_mod_dirs:
        config["updates"].extend(create_ecosystem_config("gomod", go_mod_dirs))

    if pyproject_dirs:
        config["updates"].extend(create_ecosystem_config("pip", pyproject_dirs))

    if package_json_dirs:
        config["updates"].extend(create_ecosystem_config("npm", package_json_dirs))

    # Always add GitHub Actions
    config["updates"].extend(
        create_ecosystem_config("github-actions", github_actions_dirs)
    )

    # Write the configuration file
    dependabot_file = root / ".github" / "dependabot.yml"
    dependabot_file.parent.mkdir(exist_ok=True)

    contents = yaml.safe_dump(config, sort_keys=False)
    print(f"Writing dependabot config to {dependabot_file}")

    dependabot_file.write_text(
        f"""{AUTO_GEN_HEADER}

{contents}

{AUTO_GEN_HEADER}
""",
        encoding="utf-8",
    )


def load_curr():
    ON_PART = yaml.safe_load(
        r"""
    - name: Set up chrome for tests
      run: choco install googlechrome --ignore-checksums

"""
    )
    print(ON_PART)


if __name__ == "__main__":
    # load_curr()
    main()
    generate_dependabot_config()
